apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: tomer:1.0
        #imagePullPolicy: Never
        ports:
        - containerPort: 8080

--- 

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  # externalIPs:
  #   - 192.168.0.12
  ports:
  - port: 8085
    targetPort: 8080